[build-system]
requires = ["hatchling>=1.24"]
build-backend = "hatchling.build"

[project]
name = "maomao"
version = "1.1.0"
description = "Python workflows for constructing MAOMAO, an ontology-guided FAIR resource for harmonized peptide toxicity data."
readme = "README.md"
requires-python = ">=3.11,<3.13"
license = { file = "LICENSE" }

authors = [
    { name = "Kren AI Lab", email = "krenai@umag.cl" }
]

maintainers = [
    { name = "Kren AI Lab", email = "krenai@umag.cl" }
]

keywords = [
    "peptides",
    "peptide toxicity",
    "biological data resource",
    "data integration",
    "data harmonization",
    "toxicity ontology",
    "FAIR data",
    "evidence integration",
    "annotation ambiguity",
    "protein language models",
    "benchmark datasets",
]

dependencies = [
    "pandas>=3.0.1,<4.0",
    "tqdm",
    "requests",
    "rcsb-api",
    "biopython==1.82",
    "python-dotenv",
    "pyyaml",
    "packaging==25.0",
    "typer==0.24.1",
    "click==8.3.2",
    "sylphy[all]==0.2.0",
    "biosieve==0.1.0",
    "roxy @ git+https://github.com/kren-ai-lab/roxy.git@347c493af3ac49496a7a421462508ebe8c12d7d1",
    "openpyxl",
    "seaborn"
]


[project.urls]
Homepage = "https://github.com/kren-ai-lab/maomao"
Repository = "https://github.com/kren-ai-lab/maomao"

[tool.hatch.metadata]
allow-direct-references = true

[tool.hatch.build.targets.wheel]
packages = [
    "src/maomao",
    "src/building_models",
]
